# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 806c373a47382659aca1e6c42a653b70f376892eda62f96cde66f960f304f0d6724b44bee683311b934443bff429e2f25be1017c3c83eaf144fc3de7f583faee

test:
  secret_key_base: dfc4201fa43780bb63afb455ccc83d73e867a42c826ae7185b4bf5386800c95ccff5f59027a09dd02a747c84fa45b0ee8686b6f10890be1b568d55e5979fdb9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
